services:
  - type: web
    name: angular-app
    env: static
    buildCommand: npm run build -- --base-href=/ --configuration=production
    staticPublishPath: dist/project
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
